[2021-02-04 12:00:06,455][MainThread:12068][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-02-04 12:00:16,155][Thread-1:2456][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/ HTTP/1.1" 200 267]
[2021-02-04 12:00:31,300][Thread-1:2456][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/error/ HTTP/1.1" 200 61]
[2021-03-13 02:48:19,183][MainThread:18640][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 02:48:33,670][MainThread:4184][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 02:48:48,977][Thread-1:15056][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/ HTTP/1.1" 200 267]
[2021-03-13 02:48:49,198][Thread-1:15056][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-03-13 02:48:49,199][Thread-1:15056][task_id:django.server][basehttp.py:157][WARNING]["GET /favicon.ico HTTP/1.1" 404 2084]
[2021-03-13 02:48:58,477][Thread-1:15056][task_id:django.request][log.py:230][WARNING][Not Found: /news/latest/AMAZ]
[2021-03-13 02:48:58,478][Thread-1:15056][task_id:django.server][basehttp.py:157][WARNING]["GET /news/latest/AMAZ HTTP/1.1" 404 2099]
[2021-03-13 02:49:43,512][Thread-1:15056][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMAZ HTTP/1.1" 200 267]
[2021-03-13 02:50:32,828][MainThread:4184][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 02:50:33,743][MainThread:17932][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 02:50:39,020][Thread-1:6068][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMAZ HTTP/1.1" 200 267]
[2021-03-13 02:50:54,025][MainThread:17932][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 02:50:54,889][MainThread:13116][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 02:50:57,281][Thread-1:11400][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/news/latest/AMAZ]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 30, in get_latest_news
    logger.log("parameter stock is: ----> ", stock)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 1369, in log
    raise TypeError("level must be an integer")
TypeError: level must be an integer
[2021-03-13 02:50:57,283][Thread-1:11400][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/news/latest/AMAZ HTTP/1.1" 500 80145]
[2021-03-13 02:53:31,481][MainThread:13116][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 02:53:32,349][MainThread:17644][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 02:53:38,897][MainThread:17644][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 02:53:39,801][MainThread:18640][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 02:53:44,534][Thread-1:18400][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMAZ HTTP/1.1" 200 267]
[2021-03-13 02:53:55,850][MainThread:18640][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 02:53:56,778][MainThread:15400][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 02:54:00,353][Thread-1:10956][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMAZ HTTP/1.1" 200 267]
[2021-03-13 02:54:21,204][MainThread:15400][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 02:54:22,086][MainThread:9040][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 02:54:25,012][Thread-1:13368][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMAZ HTTP/1.1" 200 267]
[2021-03-13 02:54:39,080][MainThread:9040][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 02:54:39,983][MainThread:8852][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 02:54:41,906][MainThread:11980][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 02:54:44,505][Thread-1:9836][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMAZ HTTP/1.1" 200 267]
[2021-03-13 02:54:53,586][MainThread:11980][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 02:54:54,432][MainThread:10464][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 02:55:50,508][MainThread:10464][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\sta_admin\settings.py changed, reloading.]
[2021-03-13 02:55:51,421][MainThread:17128][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 02:55:54,399][Thread-1:14048][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMAZ HTTP/1.1" 200 267]
[2021-03-13 02:56:37,002][MainThread:17128][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\sta_admin\settings.py changed, reloading.]
[2021-03-13 02:56:37,831][MainThread:11268][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 02:56:40,800][Thread-1:756][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMAZ HTTP/1.1" 200 267]
[2021-03-13 03:04:50,088][MainThread:11268][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 03:04:50,946][MainThread:1208][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 03:05:29,863][MainThread:1208][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 03:05:30,839][MainThread:14116][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 03:05:37,697][Thread-1:10088][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/news/latest/AMAZ]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 32, in get_latest_news
    a, b = crawl_news(stock)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py", line 20, in crawl_news
    html_content = BeautifulSoup(urlopen(req))
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[2021-03-13 03:05:37,698][Thread-1:10088][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/news/latest/AMAZ HTTP/1.1" 500 111128]
[2021-03-13 03:06:14,267][MainThread:12476][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 03:06:51,063][MainThread:15916][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:15:04,929][MainThread:8744][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:16:30,693][MainThread:7764][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:17:49,189][MainThread:17492][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:19:32,608][MainThread:12176][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:21:09,793][MainThread:2644][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:22:17,497][MainThread:9608][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:24:59,320][MainThread:9068][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:26:28,468][MainThread:4996][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:29:01,709][MainThread:5156][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:29:57,869][MainThread:2064][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:30:48,400][MainThread:1464][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:33:40,838][MainThread:8680][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:33:48,416][Thread-6:17952][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/news/latest/AMAZ]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 32, in get_latest_news
    a, b = crawl_news(stock)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py", line 21, in crawl_news
    response = requests.get(url=url, headers=headers)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\requests\sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\requests\sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for 'Ahttps://finviz.com/quote.ashx?t=Mhttps://finviz.com/quote.ashx?t=Ahttps://finviz.com/quote.ashx?t=Z'
[2021-03-13 04:33:48,419][Thread-6:17952][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/news/latest/AMAZ HTTP/1.1" 500 108898]
[2021-03-13 04:34:17,338][MainThread:8680][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py changed, reloading.]
[2021-03-13 04:34:18,982][MainThread:16452][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:34:24,641][MainThread:16452][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py changed, reloading.]
[2021-03-13 04:34:26,403][MainThread:12380][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:34:34,868][Thread-6:10100][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/news/latest/AMAZ]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 32, in get_latest_news
    a, b = crawl_news(stock)
TypeError: 'NoneType' object is not iterable
[2021-03-13 04:34:34,870][Thread-6:10100][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/news/latest/AMAZ HTTP/1.1" 500 78605]
[2021-03-13 04:39:09,020][MainThread:4468][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:39:24,032][Thread-1:10556][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMZN HTTP/1.1" 200 1028]
[2021-03-13 04:52:58,015][Thread-3:18144][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMZN HTTP/1.1" 200 970]
[2021-03-13 04:53:47,853][Thread-3:18144][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMZN HTTP/1.1" 200 970]
[2021-03-13 04:55:33,039][MainThread:4468][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py changed, reloading.]
[2021-03-13 04:55:33,944][MainThread:7456][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:56:19,535][MainThread:7456][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py changed, reloading.]
[2021-03-13 04:56:20,485][MainThread:7164][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:57:45,902][MainThread:7164][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py changed, reloading.]
[2021-03-13 04:57:46,930][MainThread:1972][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:58:12,090][MainThread:1972][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 04:58:13,042][MainThread:11216][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:58:15,237][MainThread:10416][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 04:58:25,869][Thread-1:4808][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMZN HTTP/1.1" 200 1065]
[2021-03-13 05:01:52,398][MainThread:10416][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py changed, reloading.]
[2021-03-13 05:01:53,366][MainThread:15700][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:02:21,819][MainThread:15700][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py changed, reloading.]
[2021-03-13 05:02:22,744][MainThread:11812][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:04:46,984][MainThread:11812][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py changed, reloading.]
[2021-03-13 05:04:47,848][MainThread:11864][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:04:56,361][Thread-1:15668][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMZN HTTP/1.1" 200 1155]
[2021-03-13 05:05:38,165][MainThread:11864][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py changed, reloading.]
[2021-03-13 05:05:39,091][MainThread:1928][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:05:44,794][MainThread:1928][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py changed, reloading.]
[2021-03-13 05:05:45,801][MainThread:864][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:07:04,252][MainThread:864][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 05:07:05,224][MainThread:17400][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:08:39,075][MainThread:17400][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 05:08:40,181][MainThread:7460][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:10:42,322][MainThread:7460][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 05:10:43,159][MainThread:16196][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:23:40,182][MainThread:16196][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 05:23:41,076][MainThread:14576][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:23:47,460][MainThread:14576][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 05:23:48,375][MainThread:16812][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:23:50,787][MainThread:18316][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:24:02,693][Thread-1:14648][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/news/latest/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 35, in get_latest_news
    news = generate_score(raw_news)
TypeError: generate_score() missing 1 required positional argument: 'key'
[2021-03-13 05:24:02,694][Thread-1:14648][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/news/latest/AMZN HTTP/1.1" 500 77773]
[2021-03-13 05:24:17,554][MainThread:18316][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 05:24:18,532][MainThread:10776][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:24:23,611][Thread-1:6472][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/news/latest/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 35, in get_latest_news
    news = generate_score(raw_news, key="content")
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\SentimentalAnalyzer.py", line 18, in generate_score
    kv[scores] = scores
TypeError: unhashable type: 'dict'
[2021-03-13 05:24:23,612][Thread-1:6472][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/news/latest/AMZN HTTP/1.1" 500 83637]
[2021-03-13 05:25:52,648][MainThread:10776][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py changed, reloading.]
[2021-03-13 05:25:53,640][MainThread:11216][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:26:14,838][MainThread:11216][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\SentimentalAnalyzer.py changed, reloading.]
[2021-03-13 05:26:15,796][MainThread:18464][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:26:23,283][Thread-1:6304][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMZN HTTP/1.1" 200 2042]
[2021-03-13 05:26:55,470][MainThread:18464][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py changed, reloading.]
[2021-03-13 05:26:56,467][MainThread:19096][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:27:16,396][MainThread:19096][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py changed, reloading.]
[2021-03-13 05:27:17,413][MainThread:18108][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:27:27,464][Thread-1:16344][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMZN HTTP/1.1" 200 1899]
[2021-03-13 05:28:41,560][MainThread:18108][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 05:28:42,479][MainThread:4656][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:28:48,047][MainThread:4656][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\SentimentalAnalyzer.py changed, reloading.]
[2021-03-13 05:28:49,028][MainThread:11216][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:30:25,795][MainThread:11216][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 05:30:26,761][MainThread:5836][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-13 05:30:35,578][Thread-1:18332][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMZN HTTP/1.1" 200 1878]
[2021-03-13 05:31:01,216][MainThread:5836][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-13 05:31:02,234][MainThread:10656][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-22 21:15:04,341][MainThread:13212][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-22 21:15:20,125][Thread-1:15712][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMZN HTTP/1.1" 200 2003]
[2021-03-22 21:15:20,387][Thread-1:15712][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-03-22 21:15:20,387][Thread-1:15712][task_id:django.server][basehttp.py:157][WARNING]["GET /favicon.ico HTTP/1.1" 404 2084]
[2021-03-22 21:17:25,770][MainThread:7172][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-22 21:18:58,806][MainThread:7172][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py changed, reloading.]
[2021-03-22 21:19:00,744][MainThread:8120][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-22 21:21:59,403][MainThread:8120][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py changed, reloading.]
[2021-03-22 21:22:01,306][MainThread:3824][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-22 21:22:43,606][MainThread:14516][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-22 21:24:46,237][MainThread:14632][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-22 21:24:50,097][Thread-1:18308][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMZN HTTP/1.1" 200 3210]
[2021-03-22 21:24:54,007][Thread-1:18308][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/AMZN HTTP/1.1" 200 3210]
[2021-03-22 21:25:11,739][Thread-1:18308][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/TSLA HTTP/1.1" 200 3037]
[2021-03-23 00:37:03,625][Thread-4:17248][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/news/latest/TSLA2]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 33, in get_latest_news
    raw_news = crawl_news(stock)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py", line 40, in crawl_news
    logger.warn("Something bad happened, when crawl news data. since the Http Code is " + response.status_code)
TypeError: must be str, not int
[2021-03-23 00:37:03,627][Thread-4:17248][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/news/latest/TSLA2 HTTP/1.1" 500 78966]
[2021-03-23 00:37:59,599][MainThread:7972][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 00:39:14,199][Thread-6:7724][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/news/latest/TSLA2]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 33, in get_latest_news
    raw_news = crawl_news(stock)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\NewCollector.py", line 40, in crawl_news
    logger.warn("Something bad happened, when crawl news data. since the Http Code is " + response.status_code)
TypeError: must be str, not int
[2021-03-23 00:39:14,206][Thread-6:7724][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/news/latest/TSLA2 HTTP/1.1" 500 82057]
[2021-03-23 00:40:39,244][MainThread:14932][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 00:41:12,370][Thread-6:5348][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/TSLA2 HTTP/1.1" 200 81]
[2021-03-23 00:41:23,298][Thread-6:5348][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/TSLA3 HTTP/1.1" 200 81]
[2021-03-23 00:41:32,676][Thread-6:5348][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/TSLA HTTP/1.1" 200 3052]
[2021-03-23 01:09:06,054][MainThread:12372][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 01:09:23,550][Thread-1:2084][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/TSLA HTTP/1.1" 200 3049]
[2021-03-23 01:09:32,000][Thread-1:2084][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/TSLA2 HTTP/1.1" 200 81]
[2021-03-23 01:09:45,818][MainThread:12372][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-23 01:09:46,974][MainThread:9748][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 01:12:03,452][MainThread:9748][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-23 01:12:04,510][MainThread:18048][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 01:36:55,032][MainThread:18048][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-23 01:36:55,939][MainThread:6748][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 01:37:49,887][MainThread:6748][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-23 01:37:50,888][MainThread:6520][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:15:08,369][MainThread:6520][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-23 02:15:09,514][MainThread:16288][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:15:42,111][MainThread:16288][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-23 02:15:43,026][MainThread:6912][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:15:56,397][MainThread:6912][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-23 02:15:57,474][MainThread:2332][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:16:08,451][MainThread:2332][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-23 02:16:09,421][MainThread:492][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:17:21,641][MainThread:492][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockMetaData.py changed, reloading.]
[2021-03-23 02:17:22,683][MainThread:2028][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:18:18,181][MainThread:2028][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockMetaData.py changed, reloading.]
[2021-03-23 02:18:19,170][MainThread:16836][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:18:41,273][MainThread:16836][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockMetaData.py changed, reloading.]
[2021-03-23 02:18:42,307][MainThread:15624][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:20:14,880][MainThread:15624][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockMetaData.py changed, reloading.]
[2021-03-23 02:20:16,131][MainThread:2664][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:20:31,099][MainThread:2664][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockMetaData.py changed, reloading.]
[2021-03-23 02:20:32,168][MainThread:10136][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:20:46,512][MainThread:10136][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockMetaData.py changed, reloading.]
[2021-03-23 02:20:47,569][MainThread:2840][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:20:55,469][MainThread:2840][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockMetaData.py changed, reloading.]
[2021-03-23 02:20:56,443][MainThread:1308][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:37:42,331][MainThread:1284][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:39:54,881][MainThread:656][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:42:28,933][MainThread:12376][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:43:55,854][MainThread:17536][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:44:37,127][MainThread:18256][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:50:32,787][MainThread:2364][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:52:37,188][MainThread:17468][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:54:02,065][MainThread:1340][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 02:58:21,552][MainThread:6280][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 03:56:12,453][MainThread:8548][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 03:57:45,978][Thread-6:18340][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 96]
[2021-03-23 03:57:46,261][Thread-6:18340][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-03-23 03:57:46,261][Thread-6:18340][task_id:django.server][basehttp.py:157][WARNING]["GET /favicon.ico HTTP/1.1" 404 2084]
[2021-03-23 03:58:12,761][Thread-6:18340][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 96]
[2021-03-23 03:59:45,113][MainThread:11748][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 19:43:46,337][MainThread:3512][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 19:44:19,768][MainThread:3512][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-23 19:44:20,833][MainThread:20000][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 19:44:30,574][Thread-1:12532][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/basic/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 44, in get_basic_info
    return JsonResponseResult().ok(data=data_items)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\JsonResponseResult.py", line 23, in ok
    self.__init__(data=data, code=code, msg=msg, **kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\JsonResponseResult.py", line 14, in __init__
    super().__init__(content=json.dumps(self.data), **kwargs)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Timestamp' is not JSON serializable
[2021-03-23 19:44:30,579][Thread-1:12532][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 500 134916]
[2021-03-23 19:45:11,205][MainThread:12180][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 19:47:10,362][Thread-6:17228][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 152090]
[2021-03-23 19:47:34,861][MainThread:17732][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 19:52:16,705][MainThread:10672][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 19:55:09,551][MainThread:10672][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-23 19:55:11,687][MainThread:18168][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 19:58:29,397][MainThread:18952][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 19:59:16,798][Thread-6:15224][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/basic/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 44, in get_basic_info
    return JsonResponseResult().ok(data=data_items)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\JsonResponseResult.py", line 23, in ok
    self.__init__(data=data, code=code, msg=msg, **kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\JsonResponseResult.py", line 14, in __init__
    super().__init__(content=json.dumps(self.data), **kwargs)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Timestamp' is not JSON serializable
[2021-03-23 19:59:16,808][Thread-6:15224][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 500 137860]
[2021-03-23 20:00:13,065][Thread-6:15224][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 152090]
[2021-03-23 20:00:55,115][MainThread:18952][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-23 20:00:56,900][MainThread:1256][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 20:01:08,536][MainThread:1256][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-23 20:01:10,310][MainThread:6504][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 20:01:18,603][Thread-6:1936][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 152038]
[2021-03-23 20:01:35,383][MainThread:6504][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-23 20:01:37,160][MainThread:19108][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 20:01:44,033][Thread-6:6740][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 143752]
[2021-03-23 20:01:50,432][MainThread:19108][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-23 20:01:52,321][MainThread:15676][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 20:02:01,911][Thread-6:3868][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 143752]
[2021-03-23 20:02:20,468][Thread-6:3868][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/TSLA HTTP/1.1" 200 137528]
[2021-03-23 20:02:49,186][MainThread:15608][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 20:03:17,548][Thread-6:20428][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/TSLA HTTP/1.1" 200 155554]
[2021-03-23 20:03:56,962][Thread-6:20428][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 125021]
[2021-03-23 20:12:04,746][MainThread:15608][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-23 20:12:06,583][MainThread:6596][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 20:18:50,998][MainThread:6596][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-23 20:18:52,777][MainThread:17732][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 20:42:19,008][MainThread:17732][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-23 20:42:20,741][MainThread:11776][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 20:44:04,571][MainThread:11776][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-23 20:44:09,159][MainThread:18372][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 20:44:17,304][Thread-6:19644][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/basic/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 42, in get_basic_info
    data_items = generator.download_basic_info()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py", line 40, in download_basic_info
    data = data[data['Date'] >= self._stock.get_start_date()].copy()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\ops\common.py", line 65, in new_method
    return method(self, other)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\ops\__init__.py", line 370, in wrapper
    res_values = comparison_op(lvalues, rvalues, op)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\ops\array_ops.py", line 244, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\ops\array_ops.py", line 56, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "pandas\_libs\ops.pyx", line 103, in pandas._libs.ops.scalar_compare
TypeError: '>=' not supported between instances of 'str' and 'datetime.datetime'
[2021-03-23 20:44:17,313][Thread-6:19644][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 500 108015]
[2021-03-23 20:45:16,648][MainThread:18372][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-23 20:45:18,417][MainThread:1468][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 20:45:27,083][Thread-6:16452][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 120129]
[2021-03-23 20:45:40,934][Thread-6:16452][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2014-01-01/AMZN HTTP/1.1" 200 96]
[2021-03-23 20:46:42,841][MainThread:1824][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 20:48:37,069][Thread-6:19292][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2014-01-01/AMZN HTTP/1.1" 200 96]
[2021-03-23 20:49:00,990][MainThread:4616][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 20:52:09,374][MainThread:18756][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 20:52:16,501][MainThread:19104][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 20:53:51,349][Thread-6:3304][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/basic/2014-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\indexes\base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 42, in get_basic_info
    data_items = generator.download_basic_info()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py", line 48, in download_basic_info
    data = data[data['Date'] >= self._stock.get_start_date().strftime("%Y%m%d")].copy()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\indexes\base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'Date'
[2021-03-23 20:53:57,626][Thread-6:3304][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/basic/2014-01-01/AMZN HTTP/1.1" 500 148891]
[2021-03-23 20:57:16,575][MainThread:19104][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-23 20:57:18,422][MainThread:16824][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 20:59:27,887][MainThread:11520][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 21:01:37,532][MainThread:4324][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 21:02:08,630][Thread-6:19356][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/basic/2014-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\indexes\base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 42, in get_basic_info
    data_items = generator.download_basic_info()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py", line 48, in download_basic_info
    ss = len(data['Date'])
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\indexes\base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'Date'
[2021-03-23 21:02:23,977][Thread-6:19356][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/basic/2014-01-01/AMZN HTTP/1.1" 500 148841]
[2021-03-23 21:06:41,609][MainThread:2676][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 21:06:50,537][Thread-6:3644][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2014-01-01/AMZN HTTP/1.1" 200 146123]
[2021-03-23 21:07:19,616][Thread-6:3644][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2014-01-01/AMZN HTTP/1.1" 200 143752]
[2021-03-23 21:09:30,610][MainThread:8560][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 21:10:14,551][MainThread:11104][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 21:11:58,617][MainThread:12024][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-23 21:12:17,668][Thread-6:15380][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2014-01-01/AMZN HTTP/1.1" 200 167861]
[2021-03-23 21:12:33,777][MainThread:12024][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-23 21:12:35,558][MainThread:5740][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 01:21:46,184][MainThread:13704][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 01:22:17,072][Thread-1:7924][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\indexes\base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 55, in predict_future_price
    x_test, y_test, test_dataset = generator.generate_future_data()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py", line 118, in generate_future_data
    training_data = data[data['Date'] < self._stock.get_validation_date()].copy()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\indexes\base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'Date'
[2021-03-24 01:22:17,079][Thread-1:7924][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 500 150249]
[2021-03-24 01:22:17,536][Thread-1:7924][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-03-24 01:22:17,537][Thread-1:7924][task_id:django.server][basehttp.py:157][WARNING]["GET /favicon.ico HTTP/1.1" 404 2084]
[2021-03-24 01:23:28,569][MainThread:13704][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-24 01:23:29,646][MainThread:4572][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 01:23:43,089][Thread-1:1912][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 55, in predict_future_price
    x_test, y_test, test_dataset = generator.generate_future_data()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py", line 127, in generate_future_data
    tomorrow_date = latest_date + timedelta(1)
TypeError: must be str, not datetime.timedelta
[2021-03-24 01:23:43,091][Thread-1:1912][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 500 90305]
[2021-03-24 01:37:32,587][MainThread:11576][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 01:44:52,055][MainThread:1692][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 01:45:27,365][Thread-6:8784][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 55, in predict_future_price
    x_test, y_test, test_dataset = generator.generate_future_data()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py", line 87, in generate_future_data
    latest_date = datetime.timestamp(test_data[-1:]['Close'].idxmin())
TypeError: descriptor 'timestamp' requires a 'datetime.datetime' object but received a 'str'
[2021-03-24 01:45:27,375][Thread-6:8784][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 500 93451]
[2021-03-24 01:46:22,952][MainThread:1692][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-24 01:46:24,742][MainThread:5404][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 01:46:36,972][Thread-6:8088][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 55, in predict_future_price
    x_test, y_test, test_dataset = generator.generate_future_data()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py", line 89, in generate_future_data
    tomorrow_date = latest_date + timedelta(1)
TypeError: unsupported operand type(s) for +: 'float' and 'datetime.timedelta'
[2021-03-24 01:46:36,977][Thread-6:8088][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 500 93687]
[2021-03-24 01:47:35,567][MainThread:5404][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-24 01:47:37,400][MainThread:7924][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 01:52:38,298][MainThread:15608][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 01:53:33,375][Thread-6:17572][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 55, in predict_future_price
    x_test, y_test, test_dataset = generator.generate_future_data()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py", line 116, in generate_future_data
    test_scaled = min_max.fit_transform(test_data)
AttributeError: 'numpy.ndarray' object has no attribute 'fit_transform'
[2021-03-24 01:53:33,382][Thread-6:17572][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 500 102697]
[2021-03-24 02:01:34,570][MainThread:15608][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-24 02:01:36,391][MainThread:8536][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 02:01:55,157][MainThread:8536][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-24 02:01:56,928][MainThread:1656][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 02:02:27,024][MainThread:15284][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 02:02:41,453][Thread-6:2424][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 58, in predict_future_price
    return JsonResponseResult().ok(data=x_test)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\JsonResponseResult.py", line 23, in ok
    self.__init__(data=data, code=code, msg=msg, **kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\JsonResponseResult.py", line 10, in __init__
    if not data: data = list()
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2021-03-24 02:02:41,457][Thread-6:2424][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 500 95562]
[2021-03-24 02:03:14,498][MainThread:15284][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-24 02:03:16,297][MainThread:13596][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 02:03:23,380][MainThread:13596][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py changed, reloading.]
[2021-03-24 02:03:25,228][MainThread:6040][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 02:03:35,337][Thread-6:16620][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 200 38]
[2021-03-24 02:55:25,251][MainThread:13372][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 02:55:36,475][MainThread:13372][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py changed, reloading.]
[2021-03-24 02:55:38,475][MainThread:13696][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:01:57,017][MainThread:4100][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:05:12,890][MainThread:18656][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:26:48,927][MainThread:9564][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:27:06,613][Thread-6:10420][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 63, in predict_future_price
    y_test = model.predict(generator)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py", line 36, in predict
    y_test = dataGenerator.get_min_max().inverse_transform(y_test)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\sklearn\preprocessing\_data.py", line 461, in inverse_transform
    X -= self.min_
ValueError: non-broadcastable output operand with shape (296,1) doesn't match the broadcast shape (296,2)
[2021-03-24 03:27:06,618][Thread-6:10420][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 500 102469]
[2021-03-24 03:28:32,252][MainThread:9564][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py changed, reloading.]
[2021-03-24 03:28:34,473][MainThread:13844][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:28:51,521][Thread-6:12184][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 63, in predict_future_price
    y_test = model.predict(generator)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py", line 40, in predict
    latest_date = datetime.strptime(test_dataset[-1:]['Close'].idxmin(), '%Y-%m-%d')
TypeError: strptime() argument 1 must be str, not Timestamp
[2021-03-24 03:28:51,524][Thread-6:12184][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 500 94417]
[2021-03-24 03:29:45,903][MainThread:13844][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py changed, reloading.]
[2021-03-24 03:29:47,975][MainThread:9268][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:30:23,429][MainThread:7960][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:30:35,741][Thread-6:19040][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 63, in predict_future_price
    y_test = model.predict(generator)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py", line 45, in predict
    y_test = np.concatenate([date_arr, y_test], axis=1)
  File "<__array_function__ internals>", line 6, in concatenate
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
[2021-03-24 03:30:35,746][Thread-6:19040][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 500 111525]
[2021-03-24 03:32:54,244][MainThread:18408][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:35:07,780][MainThread:16852][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:36:19,988][MainThread:17808][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:38:18,885][MainThread:12864][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:40:25,554][MainThread:5804][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:40:59,600][Thread-6:1048][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 63, in predict_future_price
    y_test = model.predict(generator)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py", line 41, in predict
    y_test = np.concatenate([date_arr, y_test], axis=1)
  File "<__array_function__ internals>", line 6, in concatenate
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
[2021-03-24 03:40:59,606][Thread-6:1048][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 500 115419]
[2021-03-24 03:43:52,123][MainThread:5804][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py changed, reloading.]
[2021-03-24 03:43:56,723][MainThread:20244][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:44:24,125][Thread-6:11052][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 63, in predict_future_price
    y_test = model.predict(generator)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py", line 41, in predict
    for timestamp_obj in test_dataset.index.tolist()][:len(y_test)])
  File "<__array_function__ internals>", line 6, in concatenate
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
[2021-03-24 03:44:24,131][Thread-6:11052][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 500 115574]
[2021-03-24 03:44:36,771][MainThread:20244][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py changed, reloading.]
[2021-03-24 03:44:39,058][MainThread:17388][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:45:48,139][MainThread:18532][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:46:57,818][MainThread:7584][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:47:44,733][MainThread:14812][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:50:56,490][MainThread:8352][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:52:01,452][MainThread:220][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:52:32,125][Thread-6:4184][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 65, in predict_future_price
    return JsonResponseResult().ok(data=y_test)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\JsonResponseResult.py", line 23, in ok
    self.__init__(data=data, code=code, msg=msg, **kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\JsonResponseResult.py", line 10, in __init__
    if not data: data = list()
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2021-03-24 03:52:32,130][Thread-6:4184][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 500 108340]
[2021-03-24 03:54:02,695][MainThread:220][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py changed, reloading.]
[2021-03-24 03:54:04,907][MainThread:19084][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 03:54:21,132][Thread-6:2424][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 200 8535]
[2021-03-24 03:54:30,041][Thread-6:2424][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/2015-01-01/AMZN2 HTTP/1.1" 200 99]
[2021-03-24 03:54:43,634][Thread-6:2424][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2013-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\indexes\base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 63, in predict_future_price
    y_test = model.predict(generator)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py", line 34, in predict
    x_test, _, test_dataset = dataGenerator.generate_future_data()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py", line 86, in generate_future_data
    training_data = data[data['Date'] < self._stock.get_validation_date()].copy()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\indexes\base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'Date'
[2021-03-24 03:54:43,646][Thread-6:2424][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2013-01-01/AMZN HTTP/1.1" 500 157330]
[2021-03-24 04:01:10,218][MainThread:7948][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 04:01:40,417][Thread-6:11816][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/2013-01-01/AMZN HTTP/1.1" 200 8524]
[2021-03-24 04:03:00,433][MainThread:7948][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-24 04:03:02,518][MainThread:13816][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 04:03:15,169][MainThread:19792][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 04:03:31,908][Thread-1:16408][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2012-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\indexes\base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 63, in predict_future_price
    y_test = model.predict(generator)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py", line 34, in predict
    x_test, _, test_dataset = dataGenerator.generate_future_data()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py", line 87, in generate_future_data
    training_data = data[data['Date'] < self._stock.get_validation_date()].copy()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\indexes\base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'Date'
[2021-03-24 04:03:31,914][Thread-1:16408][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2012-01-01/AMZN HTTP/1.1" 500 154376]
[2021-03-24 04:04:48,492][Thread-1:16408][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/2012-01-01/AMZN HTTP/1.1" 200 8525]
[2021-03-24 04:05:01,302][MainThread:13016][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 04:05:37,412][Thread-6:6712][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2011-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\indexes\base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 63, in predict_future_price
    y_test = model.predict(generator)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py", line 34, in predict
    x_test, _, test_dataset = dataGenerator.generate_future_data()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py", line 87, in generate_future_data
    training_data = data[data['Date'] < self._stock.get_validation_date()].copy()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\pandas\core\indexes\base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'Date'
[2021-03-24 04:05:37,423][Thread-6:6712][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2011-01-01/AMZN HTTP/1.1" 500 157330]
[2021-03-24 04:06:39,749][MainThread:13688][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 04:07:16,348][Thread-6:17592][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/2011-01-01/AMZN HTTP/1.1" 200 8530]
[2021-03-24 04:07:23,011][Thread-6:17592][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/2013-01-01/TSLA HTTP/1.1" 200 98]
[2021-03-24 04:10:16,067][MainThread:13688][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-24 04:13:07,471][MainThread:11416][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 04:13:24,458][Thread-6:11976][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2010-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 63, in predict_future_price
    y_test = model.predict(generator)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py", line 34, in predict
    x_test, _, test_dataset = dataGenerator.generate_future_data()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py", line 95, in generate_future_data
    latest_date = datetime.strptime(test_data[-1:]['Close'].idxmin(), '%Y-%m-%d')
TypeError: strptime() argument 1 must be str, not Timestamp
[2021-03-24 04:13:24,463][Thread-6:11976][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2010-01-01/AMZN HTTP/1.1" 500 96770]
[2021-03-24 04:14:04,085][Thread-6:11976][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 200 8547]
[2021-03-24 04:14:09,956][Thread-6:11976][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/2014-01-01/AMZN HTTP/1.1" 200 8535]
[2021-03-24 04:14:16,881][Thread-6:11976][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/2010-01-01/AMZN HTTP/1.1" 200 8538]
[2021-03-24 04:14:26,882][Thread-6:11976][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/2009-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 63, in predict_future_price
    y_test = model.predict(generator)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py", line 34, in predict
    x_test, _, test_dataset = dataGenerator.generate_future_data()
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py", line 95, in generate_future_data
    latest_date = datetime.strptime(test_data[-1:]['Close'].idxmin(), '%Y-%m-%d')
TypeError: strptime() argument 1 must be str, not Timestamp
[2021-03-24 04:14:26,885][Thread-6:11976][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/2009-01-01/AMZN HTTP/1.1" 500 96633]
[2021-03-24 04:15:34,367][MainThread:11416][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-24 04:15:36,601][MainThread:17328][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 04:15:54,335][MainThread:17328][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-24 04:15:56,159][MainThread:7948][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 04:16:14,030][MainThread:7948][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-24 04:16:16,019][MainThread:19108][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 04:16:44,636][MainThread:19108][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\StockDataGenerator.py changed, reloading.]
[2021-03-24 04:16:46,580][MainThread:11060][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-24 04:16:58,627][Thread-6:1648][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/2009-01-01/AMZN HTTP/1.1" 200 8538]
[2021-03-24 04:17:06,625][Thread-6:1648][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/2008-01-01/AMZN HTTP/1.1" 200 8551]
[2021-03-24 04:17:21,068][Thread-10:13256][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/TSLA HTTP/1.1" 200 3115]
[2021-03-24 04:17:21,651][Thread-10:13256][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-03-24 04:17:21,652][Thread-10:13256][task_id:django.server][basehttp.py:157][WARNING]["GET /favicon.ico HTTP/1.1" 404 2084]
[2021-03-24 04:17:24,488][Thread-6:1648][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 143752]
[2021-03-27 18:33:35,463][MainThread:13588][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-27 18:34:07,113][Thread-1:17704][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/news/latest/TSLA HTTP/1.1" 200 3184]
[2021-03-27 18:34:07,423][Thread-1:17704][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-03-27 18:34:07,424][Thread-1:17704][task_id:django.server][basehttp.py:157][WARNING]["GET /favicon.ico HTTP/1.1" 404 2084]
[2021-03-27 18:34:16,806][Thread-3:7088][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/basic/2015-01-01/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 45, in get_basic_info
    return JsonResponseResult().ok(data=data_items)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\JsonResponseResult.py", line 23, in ok
    self.__init__(data=data, code=code, msg=msg, **kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\JsonResponseResult.py", line 14, in __init__
    super().__init__(content=json.dumps(self.data), **kwargs)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Timestamp' is not JSON serializable
[2021-03-27 18:34:16,809][Thread-3:7088][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 500 136236]
[2021-03-27 18:34:17,215][Thread-3:7088][task_id:django.request][log.py:230][WARNING][Not Found: /favicon.ico]
[2021-03-27 18:34:17,216][Thread-3:7088][task_id:django.server][basehttp.py:157][WARNING]["GET /favicon.ico HTTP/1.1" 404 2084]
[2021-03-27 18:35:04,021][Thread-3:7088][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 152343]
[2021-03-27 18:35:50,886][MainThread:13072][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-27 18:40:32,615][MainThread:4844][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-27 18:41:37,445][Thread-6:19896][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/TSLA HTTP/1.1" 200 156586]
[2021-03-27 18:41:58,585][Thread-6:19896][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 152343]
[2021-03-27 18:42:03,542][Thread-6:19896][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2016-01-01/AMZN HTTP/1.1" 200 127570]
[2021-03-27 18:42:09,883][Thread-6:19896][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 152343]
[2021-03-27 18:42:17,122][Thread-6:19896][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2014-01-01/AMZN HTTP/1.1" 200 168226]
[2021-03-27 18:43:39,557][Thread-6:19896][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/2015-01-01/AMZN HTTP/1.1" 200 8545]
[2021-03-27 18:46:39,585][MainThread:16872][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-27 18:46:54,785][Thread-1:12012][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/AMZN HTTP/1.1" 200 8532]
[2021-03-27 18:47:37,715][MainThread:1208][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-27 18:49:04,985][Thread-6:16420][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/AMZN HTTP/1.1" 200 8539]
[2021-03-27 18:50:12,633][MainThread:1208][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py changed, reloading.]
[2021-03-27 18:50:14,708][MainThread:2016][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-27 18:51:21,108][MainThread:19364][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-27 18:51:39,735][MainThread:12448][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-27 18:52:31,865][MainThread:3228][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-27 18:54:30,212][MainThread:9380][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-27 18:55:06,665][Thread-6:6136][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/AMZN HTTP/1.1" 200 8562]
[2021-03-27 18:55:13,649][MainThread:9380][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py changed, reloading.]
[2021-03-27 18:55:15,629][MainThread:11808][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-27 18:55:20,138][MainThread:20192][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-27 18:55:36,388][Thread-6:12940][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/AMZN HTTP/1.1" 200 10769]
[2021-03-27 18:57:35,406][MainThread:20192][task_id:django.utils.autoreload][autoreload.py:240][INFO][D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\ModelLoader.py changed, reloading.]
[2021-03-27 18:57:41,562][MainThread:12004][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-27 18:58:11,092][Thread-6:19608][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/AMZN HTTP/1.1" 200 10099]
[2021-03-27 18:58:11,094][Thread-6:19608][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/AMZN HTTP/1.1" 500 59]
[2021-03-27 19:01:30,599][MainThread:13868][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-27 19:01:59,137][Thread-6:1264][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/predict/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 65, in predict_future_price
    return JsonResponseResult().ok(data=y_test)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\JsonResponseResult.py", line 23, in ok
    self.__init__(data=data, code=code, msg=msg, **kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\common\JsonResponseResult.py", line 10, in __init__
    if not data: data = list()
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2021-03-27 19:01:59,141][Thread-6:1264][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/predict/AMZN HTTP/1.1" 500 105485]
[2021-03-27 19:03:45,180][MainThread:3004][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-27 19:04:20,653][Thread-6:6604][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/predict/AMZN HTTP/1.1" 200 9836]
[2021-03-31 20:01:35,702][MainThread:17492][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-31 20:32:18,762][Thread-1:20816][task_id:django.request][log.py:230][WARNING][Not Found: /basic/Mon Apr 01 2019 20:32:16 GMT-0700 (Pacific Daylight Time)/AMZN]
[2021-03-31 20:32:18,763][Thread-1:20816][task_id:django.server][basehttp.py:157][WARNING]["GET /basic/Mon%20Apr%2001%202019%2020:32:16%20GMT-0700%20(Pacific%20Daylight%20Time)/AMZN HTTP/1.1" 404 2271]
[2021-03-31 20:59:34,085][Thread-3:9600][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 144359]
[2021-03-31 21:00:02,815][Thread-3:9600][task_id:django.request][log.py:230][ERROR][Internal Server Error: /analysis/basic/Mon Apr 01 2019 21:00:02 GMT-0700 (Pacific Daylight Time)/AMZN]
Traceback (most recent call last):
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\Stock_Trend_Analysis_APP\stock-trend-ana-admin\sta_admin\analysis\views.py", line 40, in get_basic_info
    start_date_obj = datetime.strptime(start_date, '%Y-%m-%d')
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "C:\Users\AARON-PREDATOR\AppData\Local\Programs\Python\Python36\lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data 'Mon Apr 01 2019 21:00:02 GMT-0700 (Pacific Daylight Time)' does not match format '%Y-%m-%d'
[2021-03-31 21:00:02,818][Thread-3:9600][task_id:django.server][basehttp.py:157][ERROR]["GET /analysis/basic/Mon%20Apr%2001%202019%2021:00:02%20GMT-0700%20(Pacific%20Daylight%20Time)/AMZN HTTP/1.1" 500 86963]
[2021-03-31 21:00:51,864][Thread-3:9600][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2019-04-02/AMZN HTTP/1.1" 200 48486]
[2021-03-31 21:01:58,691][MainThread:10504][task_id:django.utils.autoreload][autoreload.py:617][INFO][Watching for file changes with StatReloader]
[2021-03-31 21:02:48,085][Thread-6:20388][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2019-04-02/AMZN HTTP/1.1" 200 48486]
[2021-03-31 21:03:17,124][Thread-6:20388][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2019-04-02/AMZN HTTP/1.1" 200 48486]
[2021-03-31 21:04:07,092][Thread-6:20388][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2019-04-02/AMZN HTTP/1.1" 200 48486]
[2021-03-31 21:07:08,983][Thread-6:20388][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2019-04-02/AMZN HTTP/1.1" 200 48486]
[2021-03-31 21:15:47,366][Thread-11:22508][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 152620]
[2021-03-31 21:25:16,062][Thread-14:5368][task_id:django.server][basehttp.py:157][INFO]["GET /analysis/basic/2015-01-01/AMZN HTTP/1.1" 200 152620]
